In [1]:
# 基本ツール
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display
import matplotlib.ticker as ticker
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification
from sklearn import linear_model

from sklearn.metrics import mean_squared_error
# grid serch

from sklearn.model_selection import GridSearchCV

In [59]:
raw_data   = pd.read_csv('./train.csv')
raw_data_  = pd.read_csv('./test.csv')
sample_submission  = pd.read_csv('./sample_submission.csv')
train_data = raw_data.copy()
test_data  = raw_data_.copy()

In [60]:
#my_report = sweetviz.compare([train_data, 'Train'], [test_data, 'Test'], 'target')
#my_report.show_html('Report.html')

In [61]:
train_data.head(100)

,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,...,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,target
0,1,A,B,A,A,B,D,A,E,C,...,0.881122,0.421650,0.741413,0.895799,0.802461,0.724417,0.701915,0.877618,0.719903,6.994023
1,2,B,A,A,A,B,B,A,E,A,...,0.440011,0.346230,0.278495,0.593413,0.546056,0.613252,0.741289,0.326679,0.808464,8.071256
2,3,A,A,A,C,B,D,A,B,C,...,0.914155,0.369602,0.832564,0.865620,0.825251,0.264104,0.695561,0.869133,0.828352,5.760456
3,4,A,A,A,C,B,D,A,E,G,...,0.934138,0.578930,0.407313,0.868099,0.794402,0.494269,0.698125,0.809799,0.614766,7.806457
4,6,A,B,A,A,B,B,A,E,C,...,0.382600,0.705940,0.325193,0.440967,0.462146,0.724447,0.683073,0.343457,0.297743,6.868974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,164,A,B,A,C,B,B,A,E,E,...,0.198953,0.304955,0.228038,0.165184,0.350502,0.231549,0.265881,0.351718,0.251234,8.574307
96,165,A,B,A,D,B,B,A,E,C,...,0.390233,0.406308,0.254529,0.401283,0.443222,0.611084,0.373161,0.329228,0.289662,7.613036
97,167,A,B,A,C,B,D,A,E,E,...,0.435150,0.340275,0.260918,0.311286,0.611101,0.568261,0.397329,0.650514,0.805869,7.691082
98,168,A,B,A,C,C,D,A,E,G,...,0.679719,0.480595,0.484355,0.913394,0.840664,0.577120,0.346455,0.893273,0.671947,8.441794
99,169,A,B,A,A,B,B,A,E,C,...,0.385156,0.406584,0.330620,0.472851,0.566788,0.418908,0.414795,0.345924,0.274370,7.038923

In [62]:
def kesson_table(df):
    null_val = df.isnull().sum()
    percent  = 100 * df.isnull().sum() / len(df)
    kesson_table = pd.concat([null_val, percent], axis=1)
    kesson_table_ren_columns = kesson_table.rename(columns = {0 : '欠損数', 1 : '%'})
    return kesson_table_ren_columns

print('train_data')
display(kesson_table(train_data))
display(kesson_table(test_data))

train_data

        欠損数    %
id        0  0.0
cat0      0  0.0
cat1      0  0.0
cat2      0  0.0
cat3      0  0.0
cat4      0  0.0
cat5      0  0.0
cat6      0  0.0
cat7      0  0.0
cat8      0  0.0
cat9      0  0.0
cont0     0  0.0
cont1     0  0.0
cont2     0  0.0
cont3     0  0.0
cont4     0  0.0
cont5     0  0.0
cont6     0  0.0
cont7     0  0.0
cont8     0  0.0
cont9     0  0.0
cont10    0  0.0
cont11    0  0.0
cont12    0  0.0
cont13    0  0.0
target    0  0.0

        欠損数    %
id        0  0.0
cat0      0  0.0
cat1      0  0.0
cat2      0  0.0
cat3      0  0.0
cat4      0  0.0
cat5      0  0.0
cat6      0  0.0
cat7      0  0.0
cat8      0  0.0
cat9      0  0.0
cont0     0  0.0
cont1     0  0.0
cont2     0  0.0
cont3     0  0.0
cont4     0  0.0
cont5     0  0.0
cont6     0  0.0
cont7     0  0.0
cont8     0  0.0
cont9     0  0.0
cont10    0  0.0
cont11    0  0.0
cont12    0  0.0
cont13    0  0.0

In [63]:
X = train_data.iloc[:, 1:25]
y = train_data.iloc[:,25:]

X_test = test_data.iloc[:,1:25]

In [65]:
print(X)
print(X_test)

       cat0 cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont4  \
0         A    B    A    A    B    D    A    E    C    I  ...  0.281421
1         B    A    A    A    B    B    A    E    A    F  ...  0.282354
2         A    A    A    C    B    D    A    B    C    N  ...  0.293756
3         A    A    A    C    B    D    A    E    G    K  ...  0.769785
4         A    B    A    A    B    B    A    E    C    F  ...  0.279105
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
299995    A    B    A    C    B    B    A    E    E    L  ...  0.768447
299996    A    B    A    C    B    B    A    E    E    L  ...  0.775951
299997    A    B    A    C    B    B    A    E    C    M  ...  0.297406
299998    A    B    B    C    B    B    A    D    E    F  ...  0.758642
299999    A    A    B    A    B    D    A    E    C    K  ...  0.696047

           cont5     cont6     cont7     cont8     cont9    cont10    cont11  \
0       0.881122  0.421650  0.741413  0.895799  0.802461  0.724417  0.701915
1       0.440011  0.346230  0.278495  0.593413  0.546056  0.613252  0.741289
2       0.914155  0.369602  0.832564  0.865620  0.825251  0.264104  0.695561
3       0.934138  0.578930  0.407313  0.868099  0.794402  0.494269  0.698125
4       0.382600  0.705940  0.325193  0.440967  0.462146  0.724447  0.683073
...          ...       ...       ...       ...       ...       ...       ...
299995  0.269578  0.258655  0.363598  0.300619  0.340516  0.235711  0.383477
299996  0.197211  0.257024  0.574304  0.227035  0.322583  0.286094  0.324874
299997  0.449482  0.386172  0.476217  0.135947  0.502730  0.235788  0.316671
299998  0.363130  0.324132  0.229017  0.220888  0.515304  0.389391  0.245234
299999  0.734712  0.404145  0.497719  0.497974  0.782585  0.751251  0.608412

          cont12    cont13
0       0.877618  0.719903
1       0.326679  0.808464
2       0.869133  0.828352
3       0.809799  0.614766
4       0.343457  0.297743
...          ...       ...
299995  0.215227  0.793630
299996  0.306933  0.230902
299997  0.250286  0.349041
299998  0.303895  0.481138
299999  0.712868  0.452400

[300000 rows x 24 columns]
       cat0 cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont4  \
0         A    B    A    C    B    D    A    E    E    G  ...  0.701679
1         A    B    A    C    B    D    A    E    C    L  ...  0.277480
2         A    B    A    C    B    D    A    E    C    F  ...  0.279508
3         A    A    B    A    B    D    A    E    E    F  ...  0.479503
4         A    B    A    A    B    B    A    E    E    I  ...  0.757845
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
199995    A    A    A    C    B    D    A    E    G    L  ...  0.277365
199996    A    A    A    C    B    D    A    E    E    F  ...  0.523174
199997    A    A    A    C    B    D    A    E    C    K  ...  0.517103
199998    A    B    A    A    B    D    A    E    C    F  ...  0.279153
199999    A    B    A    C    B    C    A    E    G    H  ...  0.763246

           cont5     cont6     cont7     cont8     cont9    cont10    cont11  \
0       0.595507  0.286912  0.279884  0.202234  0.242654  0.285147  0.264308
1       0.479552  0.397436  0.476742  0.857073  0.516393  0.562065  0.730542
2       0.676395  0.695284  0.253316  0.586934  0.548555  0.836193  0.759788
3       0.759875  0.240049  0.298074  0.442475  0.596746  0.414131  0.255382
4       0.210232  0.329851  0.616663  0.170475  0.263235  0.710961  0.224045
...          ...       ...       ...       ...       ...       ...       ...
199995  0.963678  0.240482  0.686462  0.915165  0.848878  0.459598  0.590327
199996  0.232072  0.363421  0.694092  0.137002  0.319465  0.364527  0.388908
199997  0.432927  0.811876  0.328398  0.496017  0.538779  0.466338  0.643869
199998  0.837712  0.680886  0.534439  0.501588  0.809053  0.631704  0.766426
199999  0.792263  0.409425  0.285033  0.594721  0.824892  0.479586  0.683065

          cont12    cont13
0       0.653654  0.302448
1       0.318492  0.736251
2       0.333572  0.273905
3       0.589080  0.311625
4       0.285860  0.794931
...          ...       ...
199995  0.864873  0.425258
199996  0.664357  0.224215
199997  0.749590  0.457702
199998  0.937139  0.796304
199999  0.721518  0.722690

[200000 rows x 24 columns]

In [66]:
print(y)

          target
0       6.994023
1       8.071256
2       5.760456
3       7.806457
4       6.868974
...          ...
299995  8.343538
299996  7.851861
299997  7.600558
299998  8.272095
299999  6.025685

[300000 rows x 1 columns]

In [67]:
#　ダミー化
X = pd.get_dummies(X, columns=['cat0','cat1','cat2','cat3','cat4','cat5','cat6','cat7','cat8','cat9'])
X_test = pd.get_dummies(X_test, columns=['cat0','cat1','cat2','cat3','cat4','cat5','cat6','cat7','cat8','cat9'])

In [68]:
# 正規化
X = (X - np.min(X)) / (np.max(X) - np.min(X))
y = (y - np.min(y)) / (np.max(y) - np.min(y))

In [69]:
display(X)
display(X_test)

,cont0,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,...,cat9_F,cat9_G,cat9_H,cat9_I,cat9_J,cat9_K,cat9_L,cat9_M,cat9_N,cat9_O
0,0.887037,0.816091,0.171367,0.095360,0.114564,0.855691,0.359931,0.643496,0.882829,0.811322,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.463397,0.076438,0.387501,0.816060,0.115723,0.465907,0.288058,0.084307,0.583471,0.526128,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.720411,0.898964,0.477677,0.778047,0.129890,0.884880,0.310331,0.753604,0.852951,0.836672,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.696796,0.911708,0.198531,0.686162,0.721352,0.902538,0.509813,0.239914,0.855406,0.802359,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.505656,0.765785,0.516239,0.251719,0.111686,0.415176,0.630849,0.140716,0.432551,0.432796,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,0.309047,0.846382,0.205883,0.353368,0.719690,0.315305,0.204602,0.187108,0.293608,0.297509,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
299996,0.232781,0.194846,0.605575,0.067627,0.729014,0.251359,0.203048,0.441633,0.220760,0.277562,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
299997,0.380712,0.742099,0.485420,0.325038,0.134425,0.474276,0.326122,0.323148,0.130585,0.477937,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299998,0.604542,0.817289,0.668978,0.060156,0.707507,0.397972,0.267000,0.024539,0.214676,0.491923,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299999,0.496397,0.102293,0.755170,0.302129,0.629733,0.726317,0.343249,0.349122,0.488986,0.789216,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

,cont0,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,...,cat9_F,cat9_G,cat9_H,cat9_I,cat9_J,cat9_K,cat9_L,cat9_M,cat9_N,cat9_O
0,0.331261,0.551131,0.486284,0.156058,0.701679,0.595507,0.286912,0.279884,0.202234,0.242654,...,0,1,0,0,0,0,0,0,0,0
1,0.402404,0.617546,0.296852,0.187440,0.277480,0.479552,0.397436,0.476742,0.857073,0.516393,...,0,0,0,0,0,0,1,0,0,0
2,0.530677,0.618126,0.760865,0.199872,0.279508,0.676395,0.695284,0.253316,0.586934,0.548555,...,1,0,0,0,0,0,0,0,0,0
3,0.439653,0.487403,0.715786,0.192808,0.479503,0.759875,0.240049,0.298074,0.442475,0.596746,...,1,0,0,0,0,0,0,0,0,0
4,0.389844,0.752760,0.315269,0.191734,0.757845,0.210232,0.329851,0.616663,0.170475,0.263235,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,0.919265,0.111147,0.199583,0.181354,0.277365,0.963678,0.240482,0.686462,0.915165,0.848878,...,0,0,0,0,0,0,1,0,0,0
199996,0.362875,-0.020197,0.469025,0.336185,0.523174,0.232072,0.363421,0.694092,0.137002,0.319465,...,1,0,0,0,0,0,0,0,0,0
199997,0.463060,0.740421,0.446293,0.411387,0.517103,0.432927,0.811876,0.328398,0.496017,0.538779,...,0,0,0,0,0,1,0,0,0,0
199998,0.708709,0.418490,0.193004,0.862700,0.279153,0.837712,0.680886,0.534439,0.501588,0.809053,...,1,0,0,0,0,0,0,0,0,0
199999,0.646432,0.484954,0.141289,0.753487,0.763246,0.792263,0.409425,0.285033,0.594721,0.824892,...,0,0,1,0,0,0,0,0,0,0

In [70]:
X = X.iloc[:, :69]

print(X)

           cont0     cont1     cont2     cont3     cont4     cont5     cont6  \
0       0.887037  0.816091  0.171367  0.095360  0.114564  0.855691  0.359931
1       0.463397  0.076438  0.387501  0.816060  0.115723  0.465907  0.288058
2       0.720411  0.898964  0.477677  0.778047  0.129890  0.884880  0.310331
3       0.696796  0.911708  0.198531  0.686162  0.721352  0.902538  0.509813
4       0.505656  0.765785  0.516239  0.251719  0.111686  0.415176  0.630849
...          ...       ...       ...       ...       ...       ...       ...
299995  0.309047  0.846382  0.205883  0.353368  0.719690  0.315305  0.204602
299996  0.232781  0.194846  0.605575  0.067627  0.729014  0.251359  0.203048
299997  0.380712  0.742099  0.485420  0.325038  0.134425  0.474276  0.326122
299998  0.604542  0.817289  0.668978  0.060156  0.707507  0.397972  0.267000
299999  0.496397  0.102293  0.755170  0.302129  0.629733  0.726317  0.343249

           cont7     cont8     cont9  ...  cat9_E  cat9_F  cat9_G  cat9_H  \
0       0.643496  0.882829  0.811322  ...     0.0     0.0     0.0     0.0
1       0.084307  0.583471  0.526128  ...     0.0     1.0     0.0     0.0
2       0.753604  0.852951  0.836672  ...     0.0     0.0     0.0     0.0
3       0.239914  0.855406  0.802359  ...     0.0     0.0     0.0     0.0
4       0.140716  0.432551  0.432796  ...     0.0     1.0     0.0     0.0
...          ...       ...       ...  ...     ...     ...     ...     ...
299995  0.187108  0.293608  0.297509  ...     0.0     0.0     0.0     0.0
299996  0.441633  0.220760  0.277562  ...     0.0     0.0     0.0     0.0
299997  0.323148  0.130585  0.477937  ...     0.0     0.0     0.0     0.0
299998  0.024539  0.214676  0.491923  ...     0.0     1.0     0.0     0.0
299999  0.349122  0.488986  0.789216  ...     0.0     0.0     0.0     0.0

        cat9_I  cat9_J  cat9_K  cat9_L  cat9_M  cat9_N
0          1.0     0.0     0.0     0.0     0.0     0.0
1          0.0     0.0     0.0     0.0     0.0     0.0
2          0.0     0.0     0.0     0.0     0.0     1.0
3          0.0     0.0     1.0     0.0     0.0     0.0
4          0.0     0.0     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...     ...     ...
299995     0.0     0.0     0.0     1.0     0.0     0.0
299996     0.0     0.0     0.0     1.0     0.0     0.0
299997     0.0     0.0     0.0     0.0     1.0     0.0
299998     0.0     0.0     0.0     0.0     0.0     0.0
299999     0.0     0.0     1.0     0.0     0.0     0.0

[300000 rows x 69 columns]

In [13]:
X

,cont0,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,...,cat9_E,cat9_F,cat9_G,cat9_H,cat9_I,cat9_J,cat9_K,cat9_L,cat9_M,cat9_N
0,0.887037,0.816091,0.171367,0.095360,0.114564,0.855691,0.359931,0.643496,0.882829,0.811322,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.463397,0.076438,0.387501,0.816060,0.115723,0.465907,0.288058,0.084307,0.583471,0.526128,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.720411,0.898964,0.477677,0.778047,0.129890,0.884880,0.310331,0.753604,0.852951,0.836672,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.696796,0.911708,0.198531,0.686162,0.721352,0.902538,0.509813,0.239914,0.855406,0.802359,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.505656,0.765785,0.516239,0.251719,0.111686,0.415176,0.630849,0.140716,0.432551,0.432796,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,0.309047,0.846382,0.205883,0.353368,0.719690,0.315305,0.204602,0.187108,0.293608,0.297509,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299996,0.232781,0.194846,0.605575,0.067627,0.729014,0.251359,0.203048,0.441633,0.220760,0.277562,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299997,0.380712,0.742099,0.485420,0.325038,0.134425,0.474276,0.326122,0.323148,0.130585,0.477937,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
299998,0.604542,0.817289,0.668978,0.060156,0.707507,0.397972,0.267000,0.024539,0.214676,0.491923,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299999,0.496397,0.102293,0.755170,0.302129,0.629733,0.726317,0.343249,0.349122,0.488986,0.789216,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [71]:
# 重回帰分析

model = linear_model.LinearRegression()
model.fit(X,y)
coefficient = model.coef_
print(coefficient)

[[-3.19731082e-02  1.34545529e-02  1.14438452e-03 -2.25149090e-03
  -2.07369579e-03 -2.57146287e-02  1.27175985e-02  6.65854056e-03
   3.03246228e-02  1.10976998e-02 -1.03886867e-02  2.16677722e-02
   6.04859651e-03 -1.25880597e-03  4.63585481e+07  4.63585480e+07
  -5.10410247e+08 -5.10410247e+08  7.03227092e+07  7.03227092e+07
  -7.88010483e+08 -7.88010483e+08 -7.88010483e+08 -7.88010483e+08
  -3.31885283e+07 -3.31885283e+07 -3.31885283e+07 -3.31885283e+07
   3.01200909e+09  3.01200909e+09  3.01200909e+09  3.01200909e+09
  -8.48618740e+07 -8.48618739e+07 -8.48618739e+07 -8.48618740e+07
  -8.48618740e+07 -8.48618739e+07 -8.48618740e+07 -8.48618740e+07
   1.51742620e+09  1.51742620e+09  1.51742620e+09  1.51742620e+09
   1.51742620e+09  1.51742620e+09  1.51742620e+09  1.51742620e+09
   3.18690965e+09  3.18690965e+09  3.18690965e+09  3.18690965e+09
   3.18690965e+09  3.18690965e+09  3.18690965e+09 -6.85095520e-03
  -3.27414847e-03  9.15929705e-03 -3.68178707e-03  2.56587870e-02
   6.53358904e-03  9.40005470e-03  1.25698847e-03 -6.84953614e-03
  -3.18852495e-03  2.78378344e-03  1.39486238e-02  2.73272998e-03
   2.54832057e-03]]

In [30]:
# random forest

rf_model = RandomForestRegressor(random_state=1)

# max_fature　決定木作成に用いる変数の数

features = [30]

# n_estimators 決定木の数

estimates = [50]

# min_sample_split　分岐を続行するためのサンプルサイズ

min_sample = [300]

# max_depth 

depthes = [50]


# 合計パラメータ

params = {'n_estimators':estimates, 'max_features':features, 'min_samples_split':min_sample, 'max_depth':depthes}

In [31]:
X

,cont0,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,...,cat9_E,cat9_F,cat9_G,cat9_H,cat9_I,cat9_J,cat9_K,cat9_L,cat9_M,cat9_N
0,0.887037,0.816091,0.171367,0.095360,0.114564,0.855691,0.359931,0.643496,0.882829,0.811322,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.463397,0.076438,0.387501,0.816060,0.115723,0.465907,0.288058,0.084307,0.583471,0.526128,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.720411,0.898964,0.477677,0.778047,0.129890,0.884880,0.310331,0.753604,0.852951,0.836672,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.696796,0.911708,0.198531,0.686162,0.721352,0.902538,0.509813,0.239914,0.855406,0.802359,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.505656,0.765785,0.516239,0.251719,0.111686,0.415176,0.630849,0.140716,0.432551,0.432796,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,0.309047,0.846382,0.205883,0.353368,0.719690,0.315305,0.204602,0.187108,0.293608,0.297509,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299996,0.232781,0.194846,0.605575,0.067627,0.729014,0.251359,0.203048,0.441633,0.220760,0.277562,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299997,0.380712,0.742099,0.485420,0.325038,0.134425,0.474276,0.326122,0.323148,0.130585,0.477937,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
299998,0.604542,0.817289,0.668978,0.060156,0.707507,0.397972,0.267000,0.024539,0.214676,0.491923,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299999,0.496397,0.102293,0.755170,0.302129,0.629733,0.726317,0.343249,0.349122,0.488986,0.789216,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [32]:
y

          target
0       0.678425
1       0.782917
2       0.558768
3       0.757232
4       0.666295
...          ...
299995  0.809329
299996  0.761636
299997  0.737259
299998  0.802399
299999  0.584495

[300000 rows x 1 columns]

In [33]:
# 交差検証

grid_cv = GridSearchCV(estimator=rf_model, param_grid=params, cv=5)

In [34]:
print(y.values)
print(y.values.ravel())

[[0.67842485]
 [0.78291722]
 [0.55876804]
 ...
 [0.73725919]
 [0.80239876]
 [0.58449549]]
[0.67842485 0.78291722 0.55876804 ... 0.73725919 0.80239876 0.58449549]

In [35]:
grid_cv.fit(X,y.values.ravel())

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=1,
                                             verbose=0, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': [50], 'max_features': [30],
                         'min_samples_split': [300], 'n_estimators': [50]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [36]:
display(grid_cv.best_params_,grid_cv.best_score_)

{'max_depth': 50,
 'max_features': 30,
 'min_samples_split': 300,
 'n_estimators': 50}

0.07436097415523628

In [37]:
forest_grid_pred = grid_cv.best_estimator_.predict(X)
forest_grid_mse = mean_squared_error(y, forest_grid_pred)
forest_grid_rmse = np.sqrt(forest_grid_mse)
forest_grid_rmse

0.0790876276936703

In [52]:
pred = grid_cv.best_estimator_.predict(X_test)

In [55]:
# 提出

sample_submission['target'] = pred

In [56]:
# csvファイル書きだし

sample_submission.to_csv('sample_submission.csv', index=False)